# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/python-poetry/poetry
      rev: 1.2.0b1
      hooks:
        -   id: poetry-check
#        -   id: poetry-lock
#        -   id: poetry-export
#            args: ["--dev", "-f", "requirements.txt", "-o", "requirements.txt"]

  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        -   id: black
            args: [--safe]

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
        -   id: debug-statements
        -   id: trailing-whitespace
        -   id: mixed-line-ending
        -   id: check-added-large-files
            args: [ '--maxkb=1000' ]
        - id: end-of-file-fixer
          exclude: |
            (?x)^(
                tests/.*|
                .*\.svg|
                .*\.ipynb
            )$
#            Not using requirements-txt-fixer as is handled by poetry
#        -   id: requirements-txt-fixer
        -   id: check-yaml
        -   id: check-json
        -   id: pretty-format-json
            args: [ '--autofix' ]
        -   id: check-merge-conflict
        -   id: check-case-conflict
        -   id: check-docstring-first
            language_version: python3

  -   repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
        -   id: flake8
            language_version: python3

  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v3.1.0
      hooks:
        -   id: reorder-python-imports

  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.32.1
      hooks:
        -   id: pyupgrade

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.950
      hooks:
        -   id: mypy
            files: ^src/
            args: []

  -   repo: https://github.com/nbQA-dev/nbQA
      rev: 1.3.1
      hooks:
        -   id: nbqa-black
        -   id: nbqa-pyupgrade
