# Project information
site_name: Torch Trader
site_url: https://joseporiolayats.github.io/torchtrader
site_description: Automated trading framework using DL tools
site_author: Josep Oriol Ayats

# Repository
repo_url: https://github.com/joseporiolayats/torchtrader
repo_name: joseporiolayats/torchtrader

edit_uri: "" #disables edit button

# Configuration
theme:
  name: readthedocs

# Extensions
markdown_extensions:
  - admonition # alerts
  - codehilite
  - pymdownx.highlight

# Plugins
plugins:
  - search
  - mkdocstrings

# Page tree
nav:
  - Home: docs/index.md
#      - My Project: docs/index.md
  - Getting started: docs/getting_started.md
  - Application:
      - API: docs/app/api.md
      - Schemas: docs/app/schemas.md
  - Operations: src/torchtrader/main.md
  - Configurations: config/config.md
  - Reference:
      - Data: src/torchtrader/data.md
      - Eval: src/torchtrader/eval.md
#      - Models: src/torchtrader/models.md
#      - Training: src/torchtrader/train.md
#      - Inference: src/torchtrader/predict.md
#      - Utilities: src/torchtrader/utils.md
