# Project information
site_name: Torch Trader
site_url: https://joseporiolayats.github.io/torchtrader
site_description: Automated trading framework using DL tools
site_author: Josep Oriol Ayats

# Repository
repo_url: https://github.com/joseporiolayats/torchtrader
repo_name: joseporiolayats/torchtrader

edit_uri: "" #disables edit button

# Configuration
theme:
  name: material

# Extensions
markdown_extensions:
  - admonition # alerts
  - codehilite
  - pymdownx.highlight

# Plugins
plugins:
  - search
  - mkdocstrings

# Page tree
nav:
  - Home: index.md
#      - Torch Trader: docs/index.md
  - Getting started: getting_started.md
#  - Application:
#      - API: app/api.md
#      - Schemas: app/schemas.md
#  - Operations: torchtrader/main.md
#  - Configurations: config/config.md
#  - Reference:
#      - Data: src/torchtrader/data.md
#      - Eval: src/torchtrader/eval.md
#      - Models: src/torchtrader/models.md
#      - Training: src/torchtrader/train.md
#      - Inference: src/torchtrader/predict.md
#      - Utilities: src/torchtrader/utils.md
