# Project information
site_name: Torch Trader
site_url: https://joseporiolayats.github.io/torchtrader
site_description: Automated trading framework using DL tools
site_author: Josep Oriol Ayats

# Repository
repo_url: https://github.com/joseporiolayats/torchtrader
repo_name: joseporiolayats/torchtrader

edit_uri: "" #disables edit button

# Configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  pymdownx.superfences:
    # make exceptions to highlighting of code:
    custom_fences:
      - name: mermaid
        class: mermaid
        #            format: !!python/name:mermaid2.fence_mermaid
        format: mermaid2.fence_mermaid

# Extensions
markdown_extensions:
  - admonition # alerts
  - pymdownx.highlight


# Plugins
plugins:
  - search
  - mermaid2:
      arguments:
        # test if its __palette_1 (dark) or __palette_2 (light)
        # for mkdocs-material >=8.0.0
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
  - autorefs
  - mkdocstrings:
      enabled: true
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
extra_javascript:
  - extra/refresh_on_toggle_dark_light.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

# Page tree
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Definition: definition.md
  - Project Guidelines:
      - Proposal: project/proposal.md
      - Requirements: project/requirements.md
      - Architecture: project/architecture.md
      - Detailed Design: project/design_detailed.md
      - Project Plan: project/plan.md
      - Testing: project/testing.md
      - User Documentation: project/user_docs.md
      - Developer Documentation: project/dev_docs.md
      - Maintenance and Support: project/support.md
  - Application:
      - API: app/api.md
      - Schemas: app/schemas.md
  - Operations: torchtrader/operations.md
  - Configurations: config/config.md
  - Technical Analysis:
      - MA - Moving Average: ta/ma.md
      - RSI - Relative Strength Index: ta/rsi.md
      - Ichimoku Cloud: ta/ichimoku.md
  - Reference:
      - Data: torchtrader/data.md
      - Eval: torchtrader/eval.md
      - Models: torchtrader/models.md
      - Training: torchtrader/training.md
      - Inference: torchtrader/prediction.md
      - Utilities: torchtrader/utils.md

# to navigate with `/site` content correctly
use_directory_urls: true

# Live reload and keep track of directories
watch:
  - .
