# Project information
site_name: Torch Trader
site_url: https://joseporiolayats.github.io/torchtrader
site_description: Automated trading framework using DL tools
site_author: Josep Oriol Ayats

# Repository
repo_url: https://github.com/joseporiolayats/torchtrader
repo_name: joseporiolayats/torchtrader

edit_uri: "" #disables edit button

# Configuration
theme:
  name: material

# Extensions
markdown_extensions:
  - admonition # alerts
  - codehilite
  - pymdownx.highlight

# Plugins
plugins:
  - search
  - mkdocstrings:
      enabled: true
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false

# Page tree
nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Application:
      - API: app/api.md
      - Schemas: app/schemas.md
  - Operations: torchtrader/operations.md
  - Configurations: config/config.md
  - Technical Analysis:
      - Moving Average: ta/ma.md
      - Ichimoku Cloud: ta/ichimoku.md
  - Reference:
      - Data: torchtrader/data.md
      - Eval: torchtrader/eval.md
      - Models: torchtrader/models.md
      - Training: torchtrader/training.md
      - Inference: torchtrader/prediction.md
      - Utilities: torchtrader/utils.md

# to navigate with `/site` content correctly
use_directory_urls: false
